### ISSUE TITLE
Why does pages package has method "MakeRoutes" ?

### ISSUE THREAD

**Issue by Virgil-N** [vugu/vugu-site#6]
There is nothing in pages.go, but I see this in app.go:
```
pageMap := pages.MakeRoutes().WithRecursive(true).WithClean(true).Map()
```
So why does pages package has method "MakeRoutes" ?
And one more question:  what role does pages.go play in this project ?

**Comment by bradleypeabody** [comment]
MakeRoutes is generated by [vgrgen](https://github.com/vugu/vgrouter/tree/master/cmd/vgrgen).  If you run `go generate` you'll see that a .go file is generated with the MakeRoutes function.  pages.go I think might be there as some workaround to tell the code generator the package name, it shouldn't be needed but it might be some workaround, I forget.

**Comment by Virgil-N** [comment]
> MakeRoutes is generated by [vgrgen](https://github.com/vugu/vgrouter/tree/master/cmd/vgrgen). If you run `go generate` you'll see that a .go file is generated with the MakeRoutes function. pages.go I think might be there as some workaround to tell the code generator the package name, it shouldn't be needed but it might be some workaround, I forget.

I see. I will remove packages.go file.
Thanks for your reply!
